plugins {
    id 'multiloader-common'
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.dokka'
}

configurations {
    commonJava{
        canBeResolved = true
    }
    commonResources{
        canBeResolved = true
    }
}

dependencies {
    compileOnly(project(':common')) {
        capabilities {
            requireCapability "$group:$mod_id"
        }
    }
    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named("dokkaHtml") {
    dependsOn(configurations.commonJava)
    dokkaSourceSets.configureEach {
        sourceRoots.from(configurations.commonJava)
    }
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('compileKotlin') {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}