# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=0.1.0
group=dev.maksiks.twigonometry
java_version=21

# Common
minecraft_version=1.21.1
mod_name=twigonometry
mod_author=Maksiks
mod_id=twigonometry
license=MIT
credits=Maksiks

# Metadata
project_url=https://modrinth.com/mod/twigonometry
project_color=0x5DE67D
default_release_type=beta

# Modrinth Metadata
modrinth_slug=twigonometry
modrinth_id=rzCcrnEB
modrinth_game_versions=1.21.1
#
#

# CurseForge Metadata
curseforge_slug=twigonometry
curseforge_id=308702
#
curseforge_optional_dependencies=

# idk why middle english poetry with incorrectly used words either, it just hit the vibe
description=Thine shall twig, \nThou shall tweak, \nThine shall leaf, \nThou shall live. \n\nA library to ease the burden of making heavily customized modded trees
minecraft_version_range=[1.21.1, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
