plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

// Twigonometry: referencing parent properties so i dont have to write them every time, you can delete this
def parentProps = new Properties()
file('../../gradle.properties').withInputStream { parentProps.load(it) }
ext {
    root_version = parentProps.getProperty('version')
    root_minecraft_version = parentProps.getProperty('minecraft_version')
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // Twigonometry: referencing local maven, use the Modrinth maven repository instead!
    modImplementation group: 'dev.maksiks.twigonometry', name: "twigonometry-common-${root_minecraft_version}", version: "${root_version}"
}

repositories {
    mavenLocal()
    mavenCentral()
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

fabricApi {
    configureDataGeneration()
}