plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
    id 'org.jetbrains.kotlin.jvm'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

// Twigonometry: referencing parent properties so i dont have to write them every time, you can delete this
def parentProps = new Properties()
file('../../gradle.properties').withInputStream { parentProps.load(it) }
ext {
    root_version = parentProps.getProperty('version')
    root_minecraft_version = parentProps.getProperty('minecraft_version')
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'

    // Twigonometry: referencing local maven, use the Modrinth maven repository instead!
    implementation group: 'dev.maksiks.twigonometry', name: "twigonometry-common-${root_minecraft_version}", version: "${root_version}"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

repositories {
    mavenLocal()
    mavenCentral()
}
kotlin {
    jvmToolchain(21)
}